### ISSUE TITLE
2019-Apr-16 TODO

### ISSUE THREAD

**Issue by huyhd96** [Hoangdinhuy/HuyHD96#1]
- [x] Tạo branch tên develop
- [x] Checkout sang branch develop
- [x] Thêm thư viện `axios` vào trong project
- [x] Thử gọi tới 1 api bất kỳ tìm được và hiển thị kết quả với axios
